#!/bin/sh

source ~/semantics/bin/activate

echo "Specify the IP to host server on (0.0.0.0 for public IP):"
read ipname

echo "Specify the port to host server on:"
read portname

python manage.py runserver $ipname:$portname

