# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='owl',
            name='OWLfile',
            field=models.FileField(null=True, upload_to='file_uploads/'),
        ),
    ]
