# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161115_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='owl',
            name='fname',
            field=models.CharField(default='temp', max_length=20),
        ),
    ]
